# Generated by Django 4.0.5 on 2022-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='status',
            field=models.CharField(blank=True, choices=[('Новая', 'Новая'), ('Принято в работу', 'Принято в работу'), ('Выполнено', 'Выполнено')], default=None, max_length=120, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Статус'),
        ),
    ]
