# Generated by Django 4.0.5 on 2022-06-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_bb_status_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='status',
            field=models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=64, verbose_name='название'),
        ),
    ]
