# Generated by Django 4.0.5 on 2022-06-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_bb_status_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='status',
            field=models.ForeignKey(default=None, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Статус'),
        ),
    ]
