# Generated by Django 4.0.5 on 2022-06-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_bb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='status',
            field=models.ForeignKey(blank=True, default=None, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Статус'),
        ),
    ]
